version: '3.7'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: server
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ../:/var/www/html
            - /var/www/html/docker/data
            - /var/www/html/node_modules
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SERVER_PORT: ${SERVER_PORT}
    mysql:
        platform: linux/x86_64
        image: mysql:8
        container_name: mysql
        command: --max_allowed_packet=92505856 --ssl=0
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data:/data
